
# SPDX-License-Identifier: Apache-2.0
version: '2.1'

volumes:
  pgdata:
  walletstore:
  grafana-storage:
  prometheus-storage:

networks:
  mynetwork.dz:
    external:
      name: net_MyNetwork

services:

  explorerdb.mynetwork.dz:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.mynetwork.dz
    hostname: explorerdb.mynetwork.dz
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    volumes:
      - ./app/persistence/fabric/postgreSQL/db/createdb.sh:/docker-entrypoint-initdb.d/createdb.sh
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork.dz

  explorer.mynetwork.dz:
    image: hyperledger/explorer:latest
    container_name: explorer.mynetwork.dz
    hostname: explorer.mynetwork.dz
    environment:
      - DATABASE_HOST=explorerdb.mynetwork.dz
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./examples/My-network/config.json:/opt/explorer/app/platform/fabric/config.json
      - ./examples/My-network/connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ./examples/My-network/crypto-config:/tmp/crypto
      - ./wallet:/opt/wallet
    command: sh -c "sleep 16&& node /opt/explorer/main.js && tail -f /dev/null"
    ports:
      - 8090:8080
    networks:
      - mynetwork.dz

  proms:
    container_name: proms
    image: prom/prometheus:latest
    volumes:
      - ./app/platform/fabric/artifacts/operations/balance-transfer/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    ports:
      - '9090:9090'
    networks:
      - mynetwork.dz

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - ./app/platform/fabric/artifacts/operations/balance-transfer/balance-transfer-grafana-dashboard.json:/var/lib/grafana/dashboards/mydashboard.json
      - ./app/platform/fabric/artifacts/operations/grafana_conf/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
    ports:
      - '3000:3000'
    networks:
      - mynetwork.dz
